<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\ColDogLocker.Core\ColDogLocker.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next"/>
        <PackageReference Include="Microsoft.Data.Sqlite.Core"/>
        <PackageReference Include="Newtonsoft.Json"/>
        <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3"/>
    </ItemGroup>

    <PropertyGroup>
        <RootNamespace>ColDogStudios.ColDogLocker.Services</RootNamespace>
    </PropertyGroup>

</Project>
