<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>ColDogStudios.ColDogLocker.Cli</RootNamespace>
        <AssemblyName>cdlocker</AssemblyName>
        <PlatformTarget>AnyCPU</PlatformTarget>

        <!-- Single File Publishing - Only applies when explicitly publishing with a RID -->
        <PublishSingleFile Condition="'$(RuntimeIdentifier)' != ''">true</PublishSingleFile>
        <SelfContained Condition="'$(RuntimeIdentifier)' != ''">true</SelfContained>
        <PublishTrimmed Condition="'$(RuntimeIdentifier)' != ''">true</PublishTrimmed>
        <IncludeNativeLibrariesForSelfExtract Condition="'$(RuntimeIdentifier)' != ''">true</IncludeNativeLibrariesForSelfExtract>

        <ApplicationIcon>..\resources\cdlIcon.ico</ApplicationIcon>
        <SignAssembly>False</SignAssembly>
        <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DebugType>none</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ColDogLocker.Core\ColDogLocker.Core.csproj"/>
        <ProjectReference Include="..\ColDogLocker.Services\ColDogLocker.Services.csproj"/>
        <ProjectReference Include="..\ColDogLocker.Tui\ColDogLocker.Tui.csproj"/>
    </ItemGroup>

</Project>
