<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ColDogStudios.ColDogLocker.Cli</RootNamespace>
    <AssemblyName>ColDogLocker</AssemblyName>
    <ApplicationIcon>..\resources\cdlIcon.ico</ApplicationIcon>
    
    <!-- Product Information -->
    <Product>ColDog Locker</Product>
    <AssemblyTitle>ColDog Locker</AssemblyTitle>
    <Description>A secure file locker application</Description>
    <Copyright>© ColDog Studios. All Rights Reserved.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColDogLocker.Core\ColDogLocker.Core.csproj" />
    <ProjectReference Include="..\ColDogLocker.Application\ColDogLocker.Application.csproj" />
    <ProjectReference Include="..\ColDogLocker.Infrastructure\ColDogLocker.Infrastructure.csproj" />
    <ProjectReference Include="..\ColDogLocker.Gui\ColDogLocker.Gui.csproj" />
    <ProjectReference Include="..\ColDogLocker.Tui\ColDogLocker.Tui.csproj" />
  </ItemGroup>

</Project>
