<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\ColDogLocker.Application\ColDogLocker.Application.csproj"/>
        <ProjectReference Include="..\ColDogLocker.Infrastructure\ColDogLocker.Infrastructure.csproj"/>
    </ItemGroup>

    <PropertyGroup>
        <RootNamespace>ColDogStudios.ColDogLocker.Tui</RootNamespace>
    </PropertyGroup>

</Project>
