name: Ask a Question
description: Ask a Question
title: "[Question]: "
labels: ["type: question"]
projects:
    - "ColDogStudios/ColDog Locker/2"
body:
    - type: markdown
      attributes:
          value: |
              > Thanks for asking a question!
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com
      validations:
          required: false
    - type: textarea
      id: what-happened
      attributes:
          label: What is your Question?
          placeholder: What is your Question?
      validations:
          required: true
    - type: dropdown
      id: version
      attributes:
          label: Version
          description: What version of ColDog Locker are you running?
          options:
              - v0.1.0-Beta
              - v0.0.4-Alpha
      validations:
          required: false
    - type: dropdown
      id: OS
      attributes:
          label: OS
          description: What OS are you using?
          options:
              - Windows 11
              - Windows 10
              - Server 2022
              - Other (put OS in description)
      validations:
          required: false
