name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["type: bug"]
projects:
    - "ColDogStudios/ColDog Locker/2"
body:
    - type: markdown
      attributes:
          value: |
              > Thanks for taking the time to fill out this bug report!
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com
      validations:
          required: false
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: A bug happened!
      validations:
          required: true
    - type: dropdown
      id: version
      attributes:
          label: Version
          description: What version of ColDog Locker are you running?
          options:
              - v0.1.0-Beta
              - v0.0.4-Alpha
      validations:
          required: true
    - type: dropdown
      id: OS
      attributes:
          label: OS
          description: What OS are you seeing the problem on?
          options:
              - Windows 11
              - Windows 10
              - Server 2022
              - Other (put OS in description)
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: Please copy and paste ColDog Locker log output.
          placeholder: Paste logs here
      validations:
          required: false
