name: Feature Request
description: Request a Feature or Enhancement
title: "Feature-Request"
labels: ["type: feature"]
projects:
    - "ColDogStudios/ColDog Locker/2"
body:
    - type: markdown
      attributes:
          value: |
              > Thanks for taking the time to fill out this feature request!
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com
      validations:
          required: false
    - type: textarea
      id: feature-problem
      attributes:
          label: Is your feature request related to a problem?
          description: Please describe a clear and concise description of what the problem is. EX. I'm always frustrated when [...]
          placeholder: Tell us what the problem is!
      validations:
          required: false
    - type: textarea
      id: new-feature
      attributes:
          label: What is the new feature you want added?
          description: Please describe a clear and concise description of what you want added, otherwise we will request more info.
          placeholder: Tell us what you want added!
      validations:
          required: true
    - type: dropdown
      id: version
      attributes:
          label: Version
          description: What version of ColDog Locker are you running?
          options:
              - v0.0.5
              - v0.0.4
      validations:
          required: true
    - type: dropdown
      id: OS
      attributes:
          label: OS
          description: What OS are you using?
          options:
              - Windows 11
              - Windows 10
              - Server 2022
              - Other (put OS in description)
      validations:
          required: false
