<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>ColDogStudios.ColDogLocker.Gui.Avalonia</RootNamespace>
        <AssemblyName>ColDogLocker</AssemblyName>
        <ApplicationIcon>Assets\cdlIcon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ColDogLocker.Core\ColDogLocker.Core.csproj"/>
        <ProjectReference Include="..\ColDogLocker.Infrastructure\ColDogLocker.Infrastructure.csproj"/>
        <!-- <ProjectReference Include="..\ColDogLocker.Application\ColDogLocker.Application.csproj" /> -->
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Assets\cdlIcon.ico"/>
    </ItemGroup>
</Project>
