<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>ColDogStudios.ColDogLocker.Avalonia</RootNamespace>
        <AssemblyName>ColDogLocker</AssemblyName>
        <ApplicationIcon>Assets\cdlIcon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="Material.Icons.Avalonia"/>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ColDogLocker.Core\ColDogLocker.Core.csproj"/>
        <ProjectReference Include="..\ColDogLocker.Services\ColDogLocker.Services.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Assets\cdlIcon.ico"/>
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="ColDogLocker.Avalonia.Tests" />
    </ItemGroup>
</Project>
