<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\ColDogLocker.Core\ColDogLocker.Core.csproj"/>
        <ProjectReference Include="..\ColDogLocker.Infrastructure\ColDogLocker.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json"/>
    </ItemGroup>

    <PropertyGroup>
        <RootNamespace>ColDogStudios.ColDogLocker.Application</RootNamespace>
    </PropertyGroup>

</Project>
