name: Greetings

on: [pull_request_target, issues]

jobs:
    greeting:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - uses: actions/first-interaction@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  issue-message: "👋 Welcome to ColDog Locker! Thank you for taking the time to report an issue. We appreciate your contribution towards improving our project. Please follow the issue template to help us address your issue more efficiently."
                  pr-message: "🎉 Congratulations on your first pull request in ColDog Locker! We're excited to review your contribution and merge it into our project. Thank you for helping us make ColDog Locker better. We encourage you to follow our contribution guidelines to ensure a smooth review process."
