# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer

name: PSScriptAnalyzer

on:
    push:
        branches: ["main", "development"]
    pull_request:
        branches: ["main", "development"]
    schedule:
        - cron: "30 20 * * *" # 5:30pm EST

permissions:
    contents: read

jobs:
    build:
        permissions:
            contents: read # for actions/checkout to fetch code
            security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        name: PSScriptAnalyzer
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            # Analyze PowerShell code
            - name: Run PSScriptAnalyzer
              uses: microsoft/psscriptanalyzer-action@v1.1
              with:
                path: .\src
                #customRulePath:
                #recureseCustomRulePath:
                #excludeRule: '"PSAvoidUsingInvokeExpression", "PSAvoidUsingConvertSecureStringWithPlainText"'
                #includeDefaultRules: '"PSAvoidUsingInvokeExpression", "PSAvoidUsingConvertSecureStringWithPlainText"'
                #includeRule:
                #severity
                recures: ture
                #suppressedOnly:
                #fix: false
                #enableExit: false
                #settings:
                output: results.sarif
                #ignorePattern:

            # Upload the SARIF file generated in the previous step
            - name: Upload SARIF results file
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: results.sarif
