name: PSScriptAnalyzer

on:
    push:
        branches: ["main", "development"]
    pull_request:
        branches: ["main", "development"]
    schedule:
        - cron: "30 20 * * *" # 5:30pm EST

jobs:
    PSScriptAnalyzer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # Analyze PowerShell code
            - name: Run PSScriptAnalyzer
              uses: microsoft/psscriptanalyzer-action@v1.0
              with:
                  path: .\src
                  recurse: true
                  severity: '"Error", "Warning"'
                  enableExit: true
                  output: results.sarif
